# Generated by Django 6.0.7 on 2026-07-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=255)),
                ('pickup_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('start_cycle_hours', models.FloatField(default=0.0)),
                ('total_distance_miles', models.FloatField()),
                ('total_duration_hours', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('total_duty_hours', models.FloatField()),
                ('route_points', models.JSONField(default=list)),
                ('carrier_name', models.CharField(default='Apex Carrier Corp', max_length=255)),
                ('vehicle_id', models.CharField(default='TRK-7742', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY_ND', 'On Duty (Not Driving)')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('start_odometer', models.FloatField(default=0.0)),
                ('end_odometer', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='routing.trip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
